//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness_App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int id { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Package Package { get; set; }
        public virtual Service Service { get; set; }
    }
}
