//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness_App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outcome
    {
        public int id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Outcome1 { get; set; }
    }
}
